---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangliang.
--- DateTime: 2018/4/27 上午11:33
---
local ObjEvent = ObjEvent
local MoverExtend = {}

function MoverExtend:BindMoveCallback(enable)
    if self.moveEnable == enable or not self.view then return end
    self.moveEnable = enable
    if enable then
        self.view:BindFollowCallback(function (x,y,z)
            self:SetPos(Vector3.new(x,y,z),false,true)
        end ,function (x,y,z)
            self:SetDir(Vector3.new(x,y,z),false,true)
        end ,function ()
            self:FollowEnd()
        end )
    else
        self.view:BindFollowCallback()
    end
end

function MoverExtend:__SetFollowee(followee)
    if self.followee == followee then return end
    self:__ClearFollowee()
    self.followee = followee
    followee:AddEventListener(ObjEvent.OBJ_RELEASE,self.CancelFollow,self)
end

function MoverExtend:__ClearFollowee()
    if self.followee then
        self.followee:RemoveEventListener(ObjEvent.OBJ_RELEASE,self.CancelFollow,self)
        self.followee = nil
    end
end

function MoverExtend:StartFollowEntity(entity,range)
    if self.view then
        self.isFollowing = true
        self:__SetFollowee(entity)
        self:BindMoveCallback(true)
        self.view:FollowEntity(entity.view,range or 0)
    end
end

function MoverExtend:StartFollowEntityOffset(entity,offset)
    if self.view then
        self.isFollowing = true
        self:__SetFollowee(entity)
        self:BindMoveCallback(true)
        self.view:FollowEntityOffset(entity.view,offset)
    end
end

function MoverExtend:StartFollowPos(pos,range)
    if self.view then
        self.isFollowing = true
        self:BindMoveCallback(true)
        self.view:FollowPos(pos,range or 0)
    end
end

function MoverExtend:CancelFollow()
    if not self.isFollowing then return end
    self.isFollowing = false
    self:__ClearFollowee()
    if self.view then
        self.view:CancelFollow()
    end
    self:OnFollowCancel()
end

function MoverExtend:FollowEnd()
    self.isFollowing = false
    self:__ClearFollowee()
    self:OnFollowEnd()
end

function MoverExtend:OnFollowCancel() end

function MoverExtend:OnFollowEnd() end

function MoverExtend:ReleaseMover()
    self:CancelFollow()
    self:BindMoveCallback(false)
end

function MoverExtend:FollowInRandomDirection(use)
    if self.view then
        self.view:FollowInRandomDirection(use)
    end
end

function MoverExtend:SimpleMove(dir)
    if self.view and self.speed then
        local movSpeed = dir:mul(self.speed)
        self.view:SimpleMove(movSpeed)
    end
end

function MoverExtend:SetSpeed(speed)
    if self.speed == speed then return end
    self.speed = speed
    if self.view then
        self.view:SetSpeed(speed)
    end
end

return MoverExtend