---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by SunShubin.
--- DateTime: 2018/4/16 下午12:09
---

local FsmState = FsmState
local MonsterAIState_Base = class("MonsterAIState_Base",FsmState)

function MonsterAIState_Base:GetStateId()
    return self.stateId
end

function MonsterAIState_Base:ctor()
    self.map = {}
end

function MonsterAIState_Base:AddTransition(transition,fsmID)
    if not self.map then
        self.map = {}
    end
    self.map[transition] = fsmID
end

function MonsterAIState_Base:DelTransition(transition)
    self.map[transition] = nil
end

return MonsterAIState_Base

