---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wade.
--- DateTime: 2018/4/16 上午11:27
---
local MonsterAI_Atk = class("MonsterAI_Atk",require("app.object.controller.monster.states.MonsterAIState_Base"))
local MonsterAIStates = require("app.object.controller.monster.MonsterAIStates")

function MonsterAI_Atk:ctor()
    self:AddTransition(MonsterAIStates.Transition.FarawayTarget,MonsterAIStates.MonsterAIState.MonsterAI_Follow)
    self:AddTransition(MonsterAIStates.Transition.Dead,MonsterAIStates.MonsterAIState.MonsterAI_Dead)
    self:AddTransition(MonsterAIStates.Transition.ClearHate,MonsterAIStates.MonsterAIState.MonsterAI_Idle)
    self:AddTransition(MonsterAIStates.Transition.AtkedByTarget,MonsterAIStates.MonsterAIState.MonsterAI_Atked)
    self:AddTransition(MonsterAIStates.Transition.NoTarget,MonsterAIStates.MonsterAIState.MonsterAI_Idle)
end

function MonsterAI_Atk:OnEnter()
    --print("enter monster atk")
    self.owner:CancelFollow()
end


function MonsterAI_Atk:OnUpdate(deltaTime)
    if self.owner:GetTarDis() > self.owner:GetAtkDis() and not self.owner:SkillIsPerform() then
        self.owner.AI:SetTransition(MonsterAIStates.Transition.FarawayTarget)
        return
    end
    if not self.owner:SkillIsPerform() then
        self.owner:SetMonsterDir()
        self.owner:Atk()
    end
end


return MonsterAI_Atk