---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wade.
--- DateTime: 2018/4/16 上午11:31
---


local MonsterAI_Follow = class("MonsterAI_Follow",require("app.object.controller.monster.states.MonsterAIState_Base"))
local MonsterAIStates = require("app.object.controller.monster.MonsterAIStates")
MonsterAI_Follow.followInterval = 0.2

function MonsterAI_Follow:ctor()
    self:AddTransition(MonsterAIStates.Transition.NearTarget,MonsterAIStates.MonsterAIState.MonsterAI_Atk)
    self:AddTransition(MonsterAIStates.Transition.FarawayTarget,MonsterAIStates.MonsterAIState.MonsterAI_Follow)
    self:AddTransition(MonsterAIStates.Transition.Dead,MonsterAIStates.MonsterAIState.MonsterAI_Dead)
    self:AddTransition(MonsterAIStates.Transition.AtkedByTarget,MonsterAIStates.MonsterAIState.MonsterAI_Atked)
    self:AddTransition(MonsterAIStates.Transition.NoTarget,MonsterAIStates.MonsterAIState.MonsterAI_Idle)
end


local dataModel = nil
function MonsterAI_Follow:OnEnter()
    print("enter follow")
    dataModel = self.owner.dataModel
    self.owner.view:SetSpeed(self.owner.dataModel:GetFightSpeed())
    self.owner.actor:Run_Fight()
    self.owner:StartFollow()
    self.followTime = MonsterAI_Follow.followInterval
    self.owner.dataModel:ResetLastActTime()

    if  dataModel:IsTimeClear() and dataModel:IsDisClear() then
        self:AddTransition(MonsterAIStates.Transition.ClearHate,MonsterAIStates.MonsterAIState.MonsterAI_OutofBattle)
    else
        self:DelTransition(MonsterAIStates.Transition.ClearHate)
    end
end

function MonsterAI_Follow:OnUpdate(deltaTime)
    self.followTime = self.followTime - deltaTime
    if self.followTime <= 0 then
        self.owner:StartFollow()
        self.followTime = MonsterAI_Follow.followInterval
    end

    if not self.owner:GetTarDis() then
        self.owner:CancelFollow()
        return
    end
    if self.owner:GetTarDis() < self.owner:GetCanAtkDis() then
        self.owner.AI:SetTransition(MonsterAIStates.Transition.NearTarget)
    end

    if dataModel:IsTimeClear() then
        if dataModel:GetLastActTime() >= dataModel:GetHateNum() then
           self.owner.AI:SetTransition(MonsterAIStates.Transition.ClearHate)
        end
    elseif dataModel:IsDisClear() then
        if dataModel:GetBeginBattlePos():distNH(self.owner:GetPos()) >= dataModel:GetHateNum() then
            self.owner.AI:SetTransition(MonsterAIStates.Transition.ClearHate)
        end
    end
end

return MonsterAI_Follow