---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangliang.
--- DateTime: 2018/4/28 上午10:44
---
---兴趣区方案
local Floor,CEIL,Max = math.floor,math.ceil,math.max
local BlockAoi = {}
local BLOCK_SIZE = 10
local Vector3 = Vector3
local pairs = pairs

function BlockAoi:Init(borderMin,borderSize)
    self.xMin = borderMin.x
    self.zMin = borderMin.z
    self.blockWidth = CEIL(borderSize.x/BLOCK_SIZE)
    self.blockHeight = CEIL(borderSize.z/BLOCK_SIZE)
    self.blockMax = self.blockWidth*self.blockHeight
    self.blocks = {}
    self.isValidated = true
end

function BlockAoi:Release()
    self.blocks = nil
    self.isValidated = false
end

function BlockAoi:CalcBlockId(pos)
    local x,z = self:__GetBlockIndex(pos)
    return x + z*self.blockWidth
end

function BlockAoi:__GetBlockIndex(pos)
    local x = Max(0,Floor((pos.x - self.xMin)/BLOCK_SIZE))
    local z = Max(0,Floor((pos.z - self.zMin)/BLOCK_SIZE))
    return x,z
end

function BlockAoi:AddEntity(entity)
    if not self.isValidated then return end
    local blockId = self:CalcBlockId(entity:GetPos())
    self:__Insert(entity,blockId)
end

function BlockAoi:__Insert(entity,blockId)
    entity.blockId = blockId
    local block = self.blocks[blockId]
    if not block then
        block = {}
        self.blocks[blockId] = block
    end
    block[entity.objId] = entity
end

function BlockAoi:RemoveEntity(entity)
    local block =self.blocks[entity.blockId]
    if not block then return end
    block[entity.blockId] = nil
    entity.blockId = nil
end

function BlockAoi:Move(entity)
    if not entity.blockId then return end
    local newBlockId = self:CalcBlockId(entity:GetPos())
    if newBlockId == entity.blockId then return end
    self:RemoveEntity(entity)
    self:__Insert(entity,newBlockId)
end

function BlockAoi:__GetCheckRange(minPos,maxPos)
    local minX,minZ = self:__GetBlockIndex(minPos)
    local maxX,maxZ = self:__GetBlockIndex(maxPos)
    return minX,minZ,maxX,maxZ
end

function BlockAoi:GetInCircle(center,radius,cb)
    local minPos = Vector3.new(center.x-radius,center.y,center.z-radius)
    local maxPos = Vector3.new(center.x + radius,center.y,center.z+radius)
    local minX,minZ,maxX,maxZ = self:__GetCheckRange(minPos,maxPos)
    for x=minX,maxX do
        for z = minZ,maxZ do
            local block = self.blocks[x+z*self.blockWidth]
            if block then
                for _,entity in pairs(block) do
                    local delta = entity:GetPos()-center
                    delta.y = 0
                    local odist = delta:magnitudeH()
                    if odist<=radius then
                        cb(entity,delta)
                    end
                end
            end
        end
    end
end

_G.BlockAoi = BlockAoi