---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangliang.
--- DateTime: 2018/4/11 上午11:55
---
--眩晕
local BuffDizzyImpl = class("BuffDizzyImpl")

function BuffDizzyImpl:Exec(owner,undo)

end
--定身
local BuffRootImpl = class("BuffRootImpl")

function BuffRootImpl:Exec(owner,undo)

end
--击飞
local BuffBlowImpl = class("BuffBlowImpl")

function BuffBlowImpl:Exec(owner,undo)

end
--击退
local BuffBackImpl = class("BuffBackImpl")

function BuffBackImpl:Exec(owner,undo)

end

return {BuffDizzyImpl,BuffRootImpl,BuffBlowImpl,BuffBackImpl}