---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangliang.
--- DateTime: 2018/4/11 下午12:06
---
local BuffValImpl = class("BuffValImpl")

function BuffValImpl:Exec(owner,undo)
    local propIdx = self.buff:GetSubType()
    local val = self.buff:GetVal()
    if undo then val = -val end
    owner.dataModel:AddPropVal(propIdx,val)
end

local BuffPecImpl = class("BuffPecImpl")

function BuffPecImpl:Exec(owner,undo)
    local propIdx = self.buff:GetSubType()
    local val = self.buff:GetVal()/10000
    if undo then val = -val end
    owner.dataModel:AddPropPec(propIdx,val)
end

local BuffHpValImpl = class("BuffHpValImpl")

function BuffHpValImpl:Exec(owner,undo)
    if undo then return end
    local val = self.buff:GetVal()
    owner.dataModel:AddHp(val)
end

local BuffHpPecImpl = class("BuffHpPecImpl")

function BuffHpPecImpl:Exec(owner,undo)
    if undo then return end
    local val = self.buff:GetVal()/10000
    owner.dataModel:AddHpPec(val)
end

return {BuffValImpl,BuffPecImpl,BuffHpValImpl,BuffHpPecImpl}