---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangliang.
--- DateTime: 2018/5/17 下午7:49
---
local Savable = {}

function Savable:MarkDirty()
    self.dirty = true
end

function Savable:IsDirty()
    return self.dirty
end

function Savable:SaveData()
    if not self.dirty then return end
    self.dirty = false
    return self:DoSaveData()
end

function Savable:LoadData(data)
    if data then
        self.dirty = false
        self:DoLoadData(data)
    else
        self.dirty = true
        self:Create()
    end
    self:PostLoadData()
end

function Savable:Create() end

function Savable:DoLoadData(data)
    self.lastSave = data
    self:Import(data)
    self:PostLoadData()
end

function Savable:PostLoadData() end

function Savable:DoSaveData()
    local data,mod = self:Export(true)
    self.lastSave = data
    return data,mod
end

function Savable:Import(data) end
function Savable:Export(modified) end

return Savable