---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangliang.
--- DateTime: 2018/4/13 下午5:21
---
local SceneItem = class("SceneItem",require("app.object.entity.Object"))
local Const = _G.Const
extendMethod(SceneItem,require("app.object.entity.extends.FighterExtend"))
SceneItem.isItem = true

local SceneItemDataModel = require("app.object.datamodel.actor.SceneItemDataModel")

local ViewSceneItem = require("app.object.view.ViewSceneItem")
local ipairs = ipairs

function SceneItem:Born(tid)
    self:CreateDataModel()
    self.dataModel:Init(tid)
end

function SceneItem:CreateDataModel()
    self.dataModel = SceneItemDataModel.new()
end

function SceneItem:CreateView()
    self.view = ViewSceneItem.new(self)
end

function SceneItem:Load()
    if self.view then return end
    self:CreateView()
    self.view:Load(self.dataModel:GetModel(),self.OnLoaded,self)
end

function SceneItem:OnLoaded()
    SceneItem.super.OnLoaded(self)
    self.view:SetUsable(self:IsUseSelectable())
end

function SceneItem:CacheLoc(loc)
    self.dataModel.loc = loc
end

function SceneItem:SetLocInfo(locIndex)
    self.dataModel:SetLocInfo(locIndex)
end

function SceneItem:GetLocInfo()
    return self.dataModel.locIndex
end

function SceneItem:Export(modified)
    if self.dataModel then
        return self.dataModel:Export(modified)
    end
end

function SceneItem:Import(data)
    self:CreateDataModel()
    self.dataModel:Import(data)
    self:PostImport()
end

function SceneItem:PostImport()

end

function SceneItem:EnterStage()
    self:Load()
end

function SceneItem:IsUseSelectable()
    return self.dataModel:IsUseSelectable()
end

function SceneItem:GetUseIcon()
    return self.dataModel:GetUseIcon()
end

function SceneItem:GetRadarIcon()
    return self.dataModel:GetRadarIcon()
end

function SceneItem:GetBox()
    return self.dataModel.box
end

function SceneItem:OnBoxClose()
    self.dataModel:OnBoxClose(self.view:SetUsable(self.dataModel:IsUseSelectable()))
end

function SceneItem:GetDropList()
    return self.dataModel:GetDropList()
end

function SceneItem:DropTo(user)
    local droplist = self:GetDropList()
    if droplist and user.isPlayer then
        for _,gen in ipairs(droplist) do
            user:AddItemToBag(gen.tid,gen.count)
        end
    end
    self.dataModel:Dead()
end

function SceneItem:OnDeadBy(user)
    self:DropTo(user)
end

function SceneItem:Dead()
    if self.view then
        self.view:SetUsable(false)
    end
end
--操作类型
function SceneItem:GetActType()
    if self.dataModel:IsBox() then
        return Const.PlayerCmdType.SEARCH
    else
        return Const.PlayerCmdType.PICK
    end

end

return SceneItem