---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangliang.
--- DateTime: 2018/3/27 下午4:24
---
local FsmState = FsmState
local ContAction = class("ContAction",FsmState)
function ContAction:GetStateId()
    return self.stateId
end
function ContAction:GetAction()
    return self.__cname
end
function ContAction:OnEnter()
    self.owner:PlayAni(self:GetAction(),self.startFade)
end
_G.ContAction = ContAction

local OnceAction = class("OnceAction",FsmState)
function OnceAction:GetStateId()
    return self.stateId
end
function OnceAction:GetAction()
    return self.__cname
end
function OnceAction:OnEnter()
    local actionTime = self.owner:PlayAni(self:GetAction(),self.startFade)
    self.leftTime = (1-self.endFade)*actionTime
end
function OnceAction:OnUpdate(deltaTime)
    self.leftTime = self.leftTime - deltaTime
    if self.leftTime <= 0 then
        self:OnActionOver()
    end
end
function OnceAction:OnActionOver()
end
_G.OnceAction = OnceAction

function registerActorState(states,id,cls,startFade,endFade)
    cls.stateId = id
    cls.startFade = startFade or 0.25
    cls.endFade = endFade or 0.25
    states[id] = cls
end