---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangliang.
--- DateTime: 2018/4/20 下午4:54
---
local ViewEffect = class("ViewEffect",require("app.object.view.ViewObject"))
local LuaUtility = CS.Game.LuaUtility
local EffectType = Const.EffectType
function ViewEffect:ctor(effectType,notAutoPlay)
    self.effectType = effectType
    self.notAutoPlay = notAutoPlay
end

function ViewEffect:SetMount(mountTrans)
    self.mountTrans = mountTrans
end

function ViewEffect:SetMountPos(pos)
    self.mountPos = pos
end

function ViewEffect:Load(res,cb,caller)
    self:DoLoad(res,LuaUtility.LoadEffect,cb,caller,self.effectType or EffectType.NONE)
end

function ViewEffect:Release()
    self.mountTrans = nil
    ViewEffect.super.Release(self)
end

function ViewEffect:OnLoaded()
    if self.mountTrans then
        self:Mount(self.mountTrans)
        self.mountTrans = nil
    end
    if self.mountPos then
        self:SetPos(self.mountPos)
    end
    if not self.notAutoPlay then
        self:Play()
    end
end

function ViewEffect:Mount(parentTrans)
    self.view:SetParent(parentTrans)
end

function ViewEffect:Play()
    self.view:Play()
end

function ViewEffect:PlayBallistic(toPos,speed)
    self.view:PlayBallistic(toPos.x,toPos.y,toPos.z,speed)
end

function ViewEffect:SetOnOver(onToEnd)
    self.view:SetOnOver(onToEnd)
end

return ViewEffect