---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangliang.
--- DateTime: 2018/3/24 下午7:16
---

local Const = {}

Const.UILayer = 5
Const.Default = 0

Const.AssetType = {
    MODEL_DUMMY = 2,
    MODEL_EXHIBIT = 8,
}

local EquipPos = {
    HAT = 1,
    CLOTH = 2,
    PANTS = 3,
    SHOES = 4,
    BAG = 5,
    POCKET = 6,--辅助位
    WEAPON = 7,--主武器位
    FOOD = 8,--食物位
}

Const.EquipPos = EquipPos

local EquipPart = {
    HEAD = 0,
    CLOTH = 1,
    PANTS = 2,
    SHOES = 3,
    HAIR = 4,
    BAG = 5,
    WEAPON = 6,
}

Const.EquipPart = EquipPart

Const.EquipPos2Part = {
    [EquipPos.CLOTH] = EquipPart.CLOTH,
    [EquipPos.PANTS] = EquipPart.PANTS,
    [EquipPos.SHOES] = EquipPart.SHOES,
    [EquipPos.BAG] = EquipPart.BAG,
    [EquipPos.POCKET] = EquipPart.WEAPON,
    [EquipPos.WEAPON] = EquipPart.WEAPON,
}

Const.ItemType =
{
    FOOD = 1, -- 食物
    TREATMENT =2, --血瓶等治疗物品
    WEAPON = 3,--武器
    ARMOR = 4,--防具
    BUILD = 5,-- 建筑
    MATERIAL = 6,-- 材料
--7 图纸
--8.buff道具
}

Const.Color = {
    GREEN = 16711935,
    WHITE = 4294967295,
    RED = 4278190335,
}

Const.LocBirthType = {
    POS = 1,
    CIRCLE = 2,
    TRIGGER = 3,
}

Const.Props = {
--生命上限	攻击	    防御	    真实伤害	    命中	    闪避	    暴击	    偏斜	     移速     造成伤害增幅	       受到伤害减免
    "hp",   "atk",	"def",  "atkTrue",  "agl",	"dex",	"crit",	"miss",	"move","damageIncrease","damageReduction"
}

Const.PropHpIdx = 1
Const.PropAtkIdx = 2

Const.PopHpType = {
    PLAYER_DMG = 0,
    MONSTER_DMG = 1,
    PLAYER_INC = 2,
}
--技能伤害区域
Const.SkillArea = {
    POINT = 1,--点
    RECT = 2,--矩形（锚点为一边宽的中点）
    CIRCLE = 3,--圆形（圆心）
    FAN = 4,--扇形（圆心）
}

--技能区域锚点，约定，目标类型的为初始时算目标，位置类型的为到达该处时算目标
Const.SkillAreaPivot = {
    SELF = 1,--自己
    TARGET = 2,--目标
    POS = 3,--释放到指定世界坐标
    TARGET_POS_1 = 4,--放技能初始时刻，目标所在的位置（世界坐标）
    TARGET_POS_2 = 5,--释放子物体时，目标所在的位置（世界坐标）
    SELF_POS = 6,--自己所在的位置
}

Const.EffectType = {
    NONE = 0,
    BALLISTIC = 1,
    TIMED_POS = 2,
}

Const.EffectPoint = {
    POS = 1,
    HEAD = 2,
    BODY = 3,
    LEG = 4,
    FOOT = 5,
    WEAPON_FIRE = 1,
    WEAPON_BODY = 2,
}

Const.MapMoveSpeed = {
    WALK = 0.083,
    RUN = 8,
    RIDE = 10
}

Const.SawPart = {
    HEAD = 1,
    UP_BODY = 2,
    DOWN_BODY = 3,
    MAX = 3,
}

Const.MaxPower = 5

Const.Camp = {
    SUMMON = 0,--.与召唤者同阵营
    PLAYER = 1,--.玩家
    NEUTRAL = 2,--.中立：与所有玩家友善
    MONSTER1 = 3,--.野怪1
    MONSTER2 = 4,--.野怪2
    MONSTER3 = 5,--.野怪3
    IsEnemy = function(self,camp1,camp2)
        if not camp1 or not camp2 then return false end
        if camp1 == self.NEUTRAL or camp2 == self.NEUTRAL then
            return false
        end
        return camp1 ~= camp2
    end,
}

Const.UseTag = {
    SCENE_ITEM = 0,
    MONSTER = 1,
    PLAYER = 2,
    --->=3为建筑
}

--怪物索敌半径
Const.MonsterSearchRadius = 15

--====WordMap====--

--linerender索引
Const.LineRenderType = {
    HOST = 0,
    ZOMBIE = 1,
}
Const.MapMoveSpeed = {
    WALK = 0.083,
    RUN = 8,
    RIDE = 10
}

Const.PlayerCmdType = {
    PICK = 1,--拾取
    SEARCH =2,--搜索
    ATK = 3,--破坏
    OPENDOOR = 4,--开门
    OPERATEITEM = 5,--操作物体
}

Const.SceneItemType = {
    BOX = 106,
}

Const.SceneOpenCondition = {
    NORMAL = 1,    --普通副本
    DROP = 2,      --空投等
    TIMESTAGE = 3, --限时副本
}
--宠物所处区域
Const.PetArea = {
    AreaA = 1,
    AreaB = 2,
    AreaC = 3,
}

--掉落类型
Const.DropType= {
    BOX = 1,
    AIR = 2,
}
--尸潮时间(s)
Const.ZombieMoveTime = 3600
Const.ZombieInHomeTime = 60

--触发副本刷新间隔(分钟)
Const.TRIGGERSPACE = 5*60

_G.Const = Const