require("app.ui.ViewManager")
require("app.ui.login.ViewLogin")
require("app.ui.common.ViewLoading")
require("app.ui.common.ViewConsole")
require("app.ui.common.ViewPop")

require("app.ui.main.ViewJoyStick")
require("app.ui.main.ViewMain")
require("app.ui.map.ViewMap")
require("app.ui.map.ViewMapUI")
require("app.ui.map.ViewMapMoveUI")
require("app.ui.main.ViewPlayerDie")
require("app.ui.test.TestImageShow")
require("app.ui.build.ViewBuilding")
require("app.ui.build.DeleteBuilding")

require("app.ui.common.ViewMenu")
require("app.ui.common.ViewBackground")
require("app.ui.blueprints.ViewBluePrints")
require("app.ui.backpack.ViewPlayerShow")
require("app.ui.backpack.ViewBackPack")
require("app.ui.backpack.ViewPack")
require("app.ui.backpack.InventoryManager")
require("app.ui.backpack.DragItemView")
require("app.ui.backpack.ViewSlotHint")

require("app.ui.workbench.ViewWorkBench")
require("app.ui.workbench.ViewClothBench")
require("app.ui.workbench.ViewFirearmsBench")
require("app.ui.workbench.WorkBenchManager")
require("app.ui.zoon.ViewPetCollect")

require("app.ui.sceneitem.ElevatorView")