---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangliang.
--- DateTime: 2018/5/16 下午2:26
---
---7.账号数据：账号、 游戏时长，nextId
---
local Time = require("app.module.system.Time")

local UserData = class("UserData",require("app.base.DataModel"))

local saveFields = {"account"}
function UserData:MarkSave()
    UserData.super.MarkSave(self)
    self:MarkFieldSave(saveFields)
end

local System = {}
extendMethod(System,require("app.base.Savable"))

function System:Create()
    self.maxId = 0
    self.user = UserData.new()
    self.time = Time.new()
    self.time:Init()
end

function System:GenId()
    self.maxId = self.maxId + 1
    self:MarkDirty()
    return self.maxId
end

function System:Export(modified)
    local data = self.lastSave or {}
    local mod = modified and {} or nil
    if self.user:IsDirty() then
        local userData,userMod = self.user:Export(modified)
        data.user = userData
        if mod then mod.user = userMod end
    end
    if self.time:IsDirty() then
        local timeData,timeMod = self.time:Export(modified)
        data.time = timeData
        if mod then mod.time = timeMod end
    end
    if data.maxId ~= self.maxId then
        data.maxId = self.maxId
        if mod then mod.maxId = self.maxId end
    end
    return data,mod
end

function System:Import(data)
    self.user = UserData.new()
    if data.user then
        self.user:Import(data.user)
    end
    self.time = Time.new()
    if data.time then
        self.time:Import(data.time)
    end
    if data.maxId then
        self.maxId = data.maxId
    end
end

function System:PostLoadData()
    self.user:BindChangeNotify(self.MarkDirty,self)
    self.time:BindChangeNotify(self.MarkDirty,self)
end

function System:MarkNeedSaveTime()
    self.time:MakeDirty()
end

function System:CurrentTime()
    return self.time:CurrentTime()
end

function System:GetGameTime()
    return self.time:GetGameTime()
end

function System:GetDayDeltaTime()
    return self.time:GetDayDeltaTime()
end

---通知过去了多少时间
function System:NotifyPassTimeFromLastSave()
    self.time:NotifyPassTime()
end

function System:EnableTimeTick(benable)
    if self.time then self.time:EnableTick(benable) end
end

_G.System = System